name: Actions test
on: 
  push:
    tags:
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        
      - name: echo context
        run: echo ${{ <context> }}