name: Input Test
on:
  workflow_dispatch:
    inputs:
      project:
        description: 'project name'
        required: true
        default: ''
      environment:
        description: 'environment(dev, test, stg, prod)'
        required: true
        default: 'dev'
      ref:
        description: 'ref'
        required: false
        default: ''
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git checkout ${{ github.event.inputs.ref }}
        if: ${{ github.event.inputs.ref != '' }}