name: Input Test
on:
  workflow_dispatch:
    inputs:
      project:
        description: 'project name'
        required: true
        default: ''
      environment:
        description: 'environment(dev, test, stg, prod)'
        required: true
        default: 'dev'
      ref:
        description: 'ref'
        required: false
        default: ''
jobs:
  build:
    if: github.event.inputs.logLevel == 'run'
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo Hello, world!