name: Input Test
on:
  workflow_dispatch:
    inputs:
      project:
        description: 'プロジェクト名を入力してください'
        required: true
        default: ''
      environment:
        description: 'デプロイ先の環境を入力してください'
        required: true
        default: 'dev'
      commit:
        description: 'コミットIDを入力してください'
        required: false
        default: ''
jobs:
  build:
    if: github.event.inputs.logLevel == 'run'
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo Hello, world!